name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  name:
    description: 'Name of the person to greet'
    required: true
    default: 'Dino'

# Define your outputs here.
outputs:
  name:
    description: 'Test output'

runs:
  using: node20
  main: dist/index.js
