name: 'Create Google Calendar Event'
description: 'Create a Google Calendar event from a GitHub Action'
author: 'stancic'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  service_account_client_email:
    description:
      'Service Account Client Email from the GCP JSON file -> "client_email"
      field'
    required: true
    default: ''
  service_account_client_private_key:
    description:
      'Service Account Private Key from the GCP JSON file -> "private_key" field'
    required: true
    default: ''
  calendar_id:
    description: 'Calendar ID from the Google Calendar Settings'
    default: ''
  summary:
    description: 'Event summary - It will show up as the title of the event'
    default: ''
  description:
    description:
      'Event description - It will show up as the description of the event'
    default: ''

# Define your outputs here.
outputs:
  response:
    description: 'Google API response'

runs:
  using: node20
  main: dist/index.js
