name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Make envfile
        uses: tmshkr/handle-env@v1.2
        with:
          env: |
            SERVICE_ACOOUNT_CLIENT_EMAIL=${{ secrets.SERVICE_ACOOUNT_CLIENT_EMAIL }}
            SERVICE_ACOOUNT_CLIENT_PRIVATE_KEY=${{  secrets.SERVICE_ACOOUNT_CLIENT_PRIVATE_KEY }}
            GOOGLE_CALENDAR_ID=${{ secrets.GOOGLE_CALENDAR_ID }}

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test

        run: npm run ci-test
